### ISSUE TITLE
can't build ruby on el:7 and sles:12

### ISSUE THREAD

**Issue by dgertych-monterail** [crohr/buildcurl#5]
http://buildcurl.com/?recipe=libyaml&version=2.4.3&target=el%3A7&prefix=%2Fusr%2Flocal

![image](https://user-images.githubusercontent.com/142751/39710913-74d1e8a8-521e-11e8-878f-6c6dc105e322.png)

@crohr Could you take a look? ^

**Comment by crohr** [comment]
Hello,

You’re trying to build libyaml, not ruby! Select ruby in the first box.

Regards,
Cyril

**Comment by dgertych-monterail** [comment]
I know, I'm still using older buildpack from `https://github.com/pkgr/heroku-buildpack-ruby.git#buildcurl` branch and under the hood it uses `libyaml` recipe. Could you fix `libyaml` recipe?

**Comment by aogail** [comment]
I think that I am hitting the same issue that @chytreg is. The RPM build for one of our Rails apps started failing recently with the following:

```
pkgr package tmp/diameter.tar.gz --version=3.2.1 --iteration=0.sss --name=diameter --disable_default_dependencies=true --tmpdir=/opt/diameter/tmp --force-os=centos-7 --after-install=/home/bjansen/diameter/rpm_build/post_install.sh
[2018-05-11T01:37:43+00:00] WARN: Missing build dependencies detected. Run the following to fix: sudo yum -q check-update ; sudo yum install -y "mysql-devel"
[2018-05-11T01:37:43+00:00] WARN: Can't create "/opt/diameter", which may be needed by some buildpacks.
-----> Fetching buildpack https://github.com/pkgr/heroku-buildpack-ruby.git at buildcurl
-----> Ruby app
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.4.1
-----> Installing dependencies using bundler 1.11.2
 !
/home/bjansen/.pkgr/buildpacks/builtin/7f03e5472376de1229ddab91b5cb7b0b9c1f3e33/heroku-buildpack-ruby/lib/language_pack/shell_helpers.rb:49:in `run!':  !     Command: 'set -o pipefail; curl -L --get --fail --retry 3 buildcurl.com -d recipe=libyaml -d version=0.1.6 -d target=$TARGET -s -o - | tar zxf - ' failed unexpectedly:
 !     
Command: 'set -o pipefail; curl -L --get --fail --retry 3 buildcurl.com -d recipe=libyaml -d version=0.1.6 -d target=$TARGET -s -o - | tar zxf - ' failed unexpectedly: (LanguagePack::Fetcher::FetchError)

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

Attempting to manually request libyaml 0.1.6 from buildcurl.com shows:

![screen shot 2018-05-10 at 6 42 38 pm](https://user-images.githubusercontent.com/4351/39902242-efcc4ade-5481-11e8-969d-c50c4b7497f9.png)

**Comment by crohr** [comment]
Hello,

Can you upgrade your pkgr install? The buildpack version that you’re using is outdated. 

Thanks,
Cyril

**Comment by aogail** [comment]
Okay. I tried updating pkgr to 1.6.0. We mount /tmp noexec and the new buildpack extracts stuff to `/tmp` and then tries to exec it. I added an `--env TMPDIR` argument to my pkgr invocation to work around that.

There seems to be something going wrong with bundler at this point. It seems like it's not finding any Gemfile and is ending up at `/` but I'm not sure, based on the following debug output, where bundler is being invoked or where is the Gemfile that is supposed to be used.

```
-----> Ruby app
[2018-05-11T17:29:05+00:00] DEBUG: Running "env -i PATH=\"$PATH\" PORT=\"3000\" TMPDIR=\"/var/bamboo/xml-data/build-dir/DIAM-DIAM-JOB1/tmp\" TARGET=\"el:7\" BUILDPACK_NODE_VERSION=\"0.6.8\" /home/bamboo/.pkgr/buildpacks/builtin/719e4e8cb9227b4e7f6a118d958174bd6045fa93/heroku-buildpack-ruby/bin/compile \"/var/bamboo/xml-
data/build-dir/DIAM-DIAM-JOB1/tmp/d20180511-9917-ai6d94/opt/diameter\" \"/var/bamboo/xml-data/build-dir/DIAM-DIAM-JOB1/tmp/d20180511-9917-ai6d94/opt/diameter/.git/cache\" \"/var/bamboo/xml-data/build-dir/DIAM-DIAM-JOB1/tmp/d20180511-991
7-fhu8ll\" "
-----> Compiling Ruby/Rails
sh: /: Is a directory
sh: line 9: /var/bamboo/xml-data/build-dir/DIAM-DIAM-JOB1/tmp/bundler/home/bjansen-as-your-home-directory-temporarily.-ruby-2.4.1

Heroku recommends you use the latest supported Ruby version listed here:
  https://devcenter.heroku.com/articles/ruby-support#supported-runtimes

For more information on syntax for declaring a Ruby version see:
  https://devcenter.heroku.com/articles/ruby-versions


Debug InformationCommand: set: No such file or directory
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 403
sh: -is-not-writable.-Bundler-will-use-: command not found
 !
 !     An error occurred while installing `/`-is-not-writable.-Bundler-will-use-`/var/bamboo/xml-data/build-dir/DIAM-DIAM-JOB1/tmp/bundler/home/bjansen'-as-your-home-directory-temporarily.-ruby-2.4.1
 !     
 !     Heroku recommends you use the latest supported Ruby version listed here:
 !     https://devcenter.heroku.com/articles/ruby-support#supported-runtimes
 !     
 !     For more information on syntax for declaring a Ruby version see:
 !     https://devcenter.heroku.com/articles/ruby-versions
 !     
 !     
 !     Debug InformationCommand: 'set -o pipefail; curl -L --fail --retry 5 --retry-delay 1 --connect-timeout 3 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/`/`-is-not-writable.-Bundler-will-use-`/var/bamboo/x
ml-data/build-dir/DIAM-DIAM-JOB1/tmp/bundler/home/bjansen'-as-your-home-directory-temporarily.-ruby-2.4.1.tgz -s -o - | tar zxf - ' failed unexpectedly:
 !     bash: -c: line 0: unexpected EOF while looking for matching ``'
 !     bash: -c: line 1: syntax error: unexpected end of file
 !
[2018-05-11T17:29:11+00:00] DEBUG: RuntimeError : compile failed
[2018-05-11T17:29:11+00:00] DEBUG: /home/bamboo/.rvm/gems/ruby-2.4.1/gems/pkgr-1.6.0/lib/pkgr/buildpack.rb:49:in `block in compile'
[2018-05-11T17:29:11+00:00] DEBUG: /home/bamboo/.rvm/gems/ruby-2.4.1/gems/pkgr-1.6.0/lib/pkgr/buildpack.rb:42:in `chdir'
[2018-05-11T17:29:11+00:00] DEBUG: /home/bamboo/.rvm/gems/ruby-2.4.1/gems/pkgr-1.6.0/lib/pkgr/buildpack.rb:42:in `compile'
[2018-05-11T17:29:11+00:00] DEBUG: /home/bamboo/.rvm/gems/ruby-2.4.1/gems/pkgr-1.6.0/lib/pkgr/builder.rb:123:in `block in compile'
[2018-05-11T17:29:11+00:00] DEBUG: /home/bamboo/.rvm/gems/ruby-2.4.1/gems/pkgr-1.6.0/lib/pkgr/builder.rb:121:in `each'
[2018-05-11T17:29:11+00:00] DEBUG: /home/bamboo/.rvm/gems/ruby-2.4.1/gems/pkgr-1.6.0/lib/pkgr/builder.rb:121:in `compile'
[2018-05-11T17:29:11+00:00] DEBUG: /home/bamboo/.rvm/gems/ruby-2.4.1/gems/pkgr-1.6.0/lib/pkgr/builder.rb:28:in `call'
[2018-05-11T17:29:11+00:00] DEBUG: /home/bamboo/.rvm/gems/ruby-2.4.1/gems/pkgr-1.6.0/lib/pkgr/dispatcher.rb:33:in `call'
[2018-05-11T17:29:11+00:00] DEBUG: /home/bamboo/.rvm/gems/ruby-2.4.1/gems/pkgr-1.6.0/lib/pkgr/cli.rb:170:in `package'
[2018-05-11T17:29:11+00:00] DEBUG: /home/bamboo/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
[2018-05-11T17:29:11+00:00] DEBUG: /home/bamboo/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
[2018-05-11T17:29:11+00:00] DEBUG: /home/bamboo/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
[2018-05-11T17:29:11+00:00] DEBUG: /home/bamboo/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
[2018-05-11T17:29:11+00:00] DEBUG: /home/bamboo/.rvm/gems/ruby-2.4.1/gems/pkgr-1.6.0/bin/pkgr:8:in `<top (required)>'
[2018-05-11T17:29:11+00:00] DEBUG: /home/bamboo/.rvm/gems/ruby-2.4.1/bin/pkgr:23:in `load'
[2018-05-11T17:29:11+00:00] DEBUG: /home/bamboo/.rvm/gems/ruby-2.4.1/bin/pkgr:23:in `<main>'
[2018-05-11T17:29:11+00:00] DEBUG: /home/bamboo/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
[2018-05-11T17:29:11+00:00] DEBUG: /home/bamboo/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by crohr** [comment]
Are you running pkgr as root? If so can you try with a non privileged user?

Cyril

**Comment by aogail** [comment]
No, I'm running it as a regular user `bamboo` which is used by our CI system.

**Comment by dmargery** [comment]
I investigated an issue producing errors similar to what @aogail has reported.

The core bug is that versions of bundler > 1.12.1 require a writeable home directory, with the definition of the home directory coming from the HOME env variable (see https://github.com/bundler/bundler/issues/4481). When HOME is not defined bundler defaults to /, that is not writeable. This generates a message (see `/`-is-not-writable.-Bundler-will-use-`/var/bamboo/` is the error output), that prevents the heroku buildpack from getting the info it is looking for with a call to `bash -c 'bundle platform --ruby'`

The bundler version used in that step is set by the heroku buildpack used, and the buildpack uses env -i (removing HOME for the environment). 

The proper fix implies a version of the heroku buildpack for ruby that is able to handle the unexpected warning from bundler. I was able to move forward by downgrading the version of pkgr used.

**Comment by nmichon** [comment]
I am unsure of what is causing the "`/-is-not-writable.-`" error but as a workaround, it is possible to use following pkgr option: `--env "HOME=/var/bamboo/"`.

This fixed the problem for me with pkgr version 1.6.0, ruby 2.1.5 and bundler 1.16.1

**Comment by aogail** [comment]
@nmichon Thanks for the pointer. Telling pkgr to set HOME got me past that bundler error.

How did you get the buildpack to use bundler 1.16.1? In my case, getting past HOME being unset got me to bundler complaining about not being the latest version, and the buildpack being unable to deal with that output.

```
-----> Ruby app
[2018-05-14T22:12:13+00:00] DEBUG: Running "env -i PATH=\"$PATH\" PORT=\"3000\" TMPDIR=\"/var/bamboo/xml-data/build-dir/DIAM-DIAM-JOB1/tmp\" HOME=\"/home/bamboo\"  TARGET=\"el:7\" BUILDPACK_NODE_VERSION=\"0.6.8\" /home/bamboo/.pkgr/buildpacks/builtin/719e4e8cb9227b4e7f6a118d958174bd6045fa93/heroku-buildpack-ruby/bin/compile \"/tmp/d20180514-26738-19by6ph/opt/diameter\" \"/tmp/d20180514-26738-19by6ph/opt/diameter/.git/cache\" \"/tmp/d20180514-26738-ulylnb\" "
-----> Compiling Ruby/Rails
sh: gem-install-bundler: command not found
sh: gem-install-bundler: command not found
 !
 !     An error occurred while installing ruby-2.4.1-The-latest-bundler-is-1.16.1,-but-you-are-currently-running-1.15.1.-To-update,-run-`gem-install-bundler`
 !     
 !     Heroku recommends you use the latest supported Ruby version listed here:
 !     https://devcenter.heroku.com/articles/ruby-support#supported-runtimes
 !     
 !     For more information on syntax for declaring a Ruby version see:
 !     https://devcenter.heroku.com/articles/ruby-versions
 !     
 !     
 !     Debug InformationCommand: 'set -o pipefail; curl -L --get --fail --retry 3 buildcurl.com -d recipe=ruby -d version=2.4.1-The-latest-bundler-is-1.16.1,-but-you-are-currently-running-1.15.1.-To-update,-run-`gem-install-bundler` -d target=$TARGET -s -o - | tar zxf - ' failed unexpectedly:
 !     bash: gem-install-bundler: command not found
```

**Comment by nmichon** [comment]
Yes i should have completed my answer, i encountered this error as well.
The solution is documented here: https://github.com/pkgr/heroku-buildpack-ruby#hacking (changing the bundler version to 1.16.1).
To try locally without forking the buildpacks repository, it is possible to copy the target buildpack (mine was `~/.pkgr/buildpacks/builtin/719e4e8cb9227b4e7f6a118d958174bd6045fa93/`), edit `lib/language_pack/ruby.rb` and calll pkgr with these options: `--no-edge --buildpacks-cache-dir BUILDPACK_PATH`
Where `BUILDPACK_PATH` is the copied equivalent of `~/.pkgr/buildpacks`

**Comment by aogail** [comment]
@nmichon Ah thanks for the pointer. I was reading Heroku docs to try to find that info but the places I was looking all said Heroku carefully selects the version of bundler, so you don't touch it. After updating to the latest bundler, my build is succeeding again.

@crohr Is it expected that we'd need to customize the buidlpack and use the latest bundler version or is there something else I should be doing to use pkgr's ruby buildpack as-is?

**Comment by dmargery** [comment]
@aogail, @crohr : my guess is the `ruby_version` method of lib/language_pack/helpers/bundler_wrapper.rb needs to be taught to handle messages from `bundle` warning that a newer version exists.

I'm missing a broken installation to suggest a patch

**Comment by crohr** [comment]
Hello, the latest buildpack is at `https://github.com/pkgr/heroku-buildpack-ruby.git#v183-1`. This is reflected in pkgr (https://github.com/crohr/pkgr/commit/fc83c0c62a9f37f9f858011dc36d08b2543eb5f4) but I need to cut an official release before you can just `gem update pkgr`.

**Comment by crohr** [comment]
pkgr 1.7.0 has been released. I'll now have a look at the issue with the HOME dir.

**Comment by crohr** [comment]
Just pushed 1.7.1 with a fix that sets a tmp `HOME` when executing the compile step of the buildpacks. This should work around the bundler issue (shudders).

Thanks to everyone for the help in debugging this, and please let me know if the fix works for you.
